const fs = require("fs");
const path = require("path");
const os = require("os");

const PROJECT_DIR = path.resolve(__dirname, "..");
const isWindows = os.platform() === "win32";

function setup() {
  console.log("\n  OpenCode Insights — Setup\n");

  const dbPath =
    process.env.OPENCODE_DB_PATH ||
    path.join(os.homedir(), ".local", "share", "opencode", "opencode.db");

  if (!fs.existsSync(dbPath)) {
    console.log(
      `  [warn] OpenCode database not found at: ${dbPath}`
    );
    console.log(
      "  Make sure OpenCode is installed and has run at least once.\n"
    );
  } else {
    console.log(`  [ok] Database found at: ${dbPath}\n`);
  }

  if (isWindows) {
    createPowerShellLauncher(dbPath);
  } else {
    createShellLauncher(dbPath);
  }

  console.log("  Setup complete!\n");
  console.log("  To auto-launch with OpenCode:");
  if (isWindows) {
    console.log(
      "    1. Run scripts/launch.ps1 to test the launcher"
    );
    console.log(
      "    2. Add it to your Startup folder or OpenCode config\n"
    );
  } else {
    console.log(
      "    1. Run scripts/launch.sh to test the launcher"
    );
    console.log(
      "    2. Add it to your crontab (@reboot) or OpenCode config\n"
    );
  }
  console.log(
    "  Or just run: npm run dev   (then open http://localhost:3777)\n"
  );
}

function createShellLauncher(dbPath) {
  const launcher = `#!/bin/bash
# OpenCode Insights Auto-Launcher
# Generated by: npm run setup

export OPENCODE_DB_PATH="${dbPath}"
PROJECT_DIR="${PROJECT_DIR}"
PORT=3777

# Check if already running
if lsof -Pi :$PORT -sTCP:LISTEN -t >/dev/null 2>&1 ; then
  echo "OpenCode Insights already running on port $PORT"
  exit 0
fi

# Start the server in background
cd "$PROJECT_DIR"
npm run start > /dev/null 2>&1 &
SERVER_PID=$!

# Wait for server to be ready
sleep 3

# Open browser
if command -v xdg-open > /dev/null 2>&1; then
  xdg-open "http://localhost:$PORT"
elif command -v open > /dev/null 2>&1; then
  open "http://localhost:$PORT"
fi

echo "OpenCode Insights started (PID: $SERVER_PID)"
`;

  const launcherPath = path.join(PROJECT_DIR, "scripts", "launch.sh");
  fs.writeFileSync(launcherPath, launcher);
  fs.chmodSync(launcherPath, "755");
  console.log(`  [ok] Created scripts/launch.sh`);
}

function createPowerShellLauncher(dbPath) {
  const launcher = `# OpenCode Insights Auto-Launcher
# Generated by: npm run setup

$env:OPENCODE_DB_PATH = "${dbPath.replace(/\\/g, '\\\\')}"
$ProjectDir = "${PROJECT_DIR}"
$Port = 3777

# Check if already running
$existing = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue
if ($existing) {
  Write-Host "OpenCode Insights already running on port $Port"
  exit 0
}

# Start the server in background
Start-Process -NoNewWindow -FilePath "cmd" -ArgumentList "/c cd /d `"$ProjectDir`" && npm run start"
$ServerPID = $LASTEXITCODE

# Wait for server to be ready
Start-Sleep -Seconds 3

# Open browser
Start-Process "http://localhost:$Port"

Write-Host "OpenCode Insights started"
`;

  const launcherPath = path.join(PROJECT_DIR, "scripts", "launch.ps1");
  fs.writeFileSync(launcherPath, launcher);
  console.log(`  [ok] Created scripts/launch.ps1`);
}

setup();
